[tasks.build-front]
script_runner = "@shell"
ignore_errors = true
script = '''
cd ../frontend
npm install
npm run build
'''

[tasks.build-tauri]
script_runner = "@shell"
script = '''
cd ../tauri-app
cargo make build-front
cargo tauri build
'''